spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
  datasource:
    url: jdbc:h2:mem:credit-universal;Mode=PostgreSQL;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
